/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib -I/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/tests/nim -o /home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/nimcache/tests/nim/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@smain.nim.c.o /home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/nimcache/tests/nim/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@smain.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NimStringDesc* x, void* ClE_0);
void* ClE_0;
} tyProc__yjDZcG8hRpOjknSYmSKIDw;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(NI, TM__V45tF8B8NBcxFcjfe7lhBw_2) (NimStringDesc* x);
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef N_CLOSURE_PTR(NI, TM__V45tF8B8NBcxFcjfe7lhBw_5) (NimStringDesc* x, void* ClE_0);
typedef NU8 tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA;
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine__systemZio_271)(FILE* f);
static N_INLINE(tySequence__qwqHTkRvwhrRyENtudHQ7g*, map__OOZOOZmain_7)(NimStringDesc** s, NI sLen_0, tyProc__yjDZcG8hRpOjknSYmSKIDw op);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_NIMCALL(void, Marker_tySequence__qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2997)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitCharSet)(NimStringDesc* s, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw seps, NI maxsplit);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__systemZassertions_56)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g*, sorted__OOZOOZmain_84)(NI* a, NI aLen_0, tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA order);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__V45tF8B8NBcxFcjfe7lhBw_4 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM__V45tF8B8NBcxFcjfe7lhBw_6, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim(10, 11) `1 <= N and N <= 100` ", 96);
STRING_LITERAL(TM__V45tF8B8NBcxFcjfe7lhBw_7, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim(11, 11) `1 <= len(input_list) and len(input_list) <= N` ", 122);
STRING_LITERAL(TM__V45tF8B8NBcxFcjfe7lhBw_8, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim(13, 15) `1 <= i and i <= 100` ", 96);
STRING_LITERAL(TM__V45tF8B8NBcxFcjfe7lhBw_10, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it", 147);
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
static N_NIMCALL(void, Marker_tySequence__qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g* a;
	NI T1_;
	a = (tySequence__qwqHTkRvwhrRyENtudHQ7g*)p;
	T1_ = (NI)0;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2564 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2564).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2564;
	framePtr__system_2564 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2997();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2564 = (*framePtr__system_2564).prev;
}
static N_INLINE(tySequence__qwqHTkRvwhrRyENtudHQ7g*, map__OOZOOZmain_7)(NimStringDesc** s, NI sLen_0, tyProc__yjDZcG8hRpOjknSYmSKIDw op) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g* result;
	nimfr_("map", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/pure/collections/sequtils.nim");
	result = NIM_NIL;
	nimln_(385, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/pure/collections/sequtils.nim");
	if ((sLen_0) < ((NI) 0) || (sLen_0) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(sLen_0, ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = (tySequence__qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_), ((NI) (sLen_0)));
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(386, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/pure/collections/sequtils.nim");
		colontmp_ = sLen_0;
		nimln_(119, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
		i_2 = ((NI) 0);
		{
			nimln_(120, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
			while (1) {
				NI TM__V45tF8B8NBcxFcjfe7lhBw_3;
				if (!(i_2 < colontmp_)) goto LA3;
				nimln_(386, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/pure/collections/sequtils.nim");
				i = i_2;
				if (i < 0 || i >= (result ? result->Sup.len : 0)){ raiseIndexError2(i,(result ? result->Sup.len : 0)-1); }
				if (i < 0 || i >= sLen_0){ raiseIndexError2(i,sLen_0-1); }
				result->data[i] = op.ClE_0? op.ClP_0(s[i], op.ClE_0):((TM__V45tF8B8NBcxFcjfe7lhBw_2)(op.ClP_0))(s[i]);
				nimln_(122, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__V45tF8B8NBcxFcjfe7lhBw_3)) { raiseOverflow(); };
				i_2 = (NI)(TM__V45tF8B8NBcxFcjfe7lhBw_3);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, main__OOZOOZmain_4)(void) {
	NI N;
	NimStringDesc* T1_;
	tySequence__qwqHTkRvwhrRyENtudHQ7g* input_list;
	NimStringDesc* T2_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* T3_;
	tyProc__yjDZcG8hRpOjknSYmSKIDw T4_;
	NI Alice_score;
	NI Bob_score;
	tySequence__qwqHTkRvwhrRyENtudHQ7g* sorted_list;
	tyArray__nHXaesL0DJZHyVS07ARPRA T65_;
	NI TM__V45tF8B8NBcxFcjfe7lhBw_17;
	nimfr_("main", "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
	nimln_(3, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
	T1_ = NIM_NIL;
	T1_ = readLine__systemZio_271(stdin);
	N = nsuParseInt(T1_);
	nimln_(4, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
	T2_ = NIM_NIL;
	T2_ = readLine__systemZio_271(stdin);
	T3_ = NIM_NIL;
	T3_ = nsuSplitCharSet(T2_, TM__V45tF8B8NBcxFcjfe7lhBw_4, ((NI) -1));
	nimZeroMem((void*)(&T4_), sizeof(tyProc__yjDZcG8hRpOjknSYmSKIDw));
	T4_.ClP_0 = ((TM__V45tF8B8NBcxFcjfe7lhBw_5) (nsuParseInt)); T4_.ClE_0 = NIM_NIL;
	input_list = map__OOZOOZmain_7((T3_) ? (T3_->data) : NIM_NIL, (T3_ ? T3_->Sup.len : 0), T4_);
	Alice_score = (NI)0;
	Bob_score = (NI)0;
	nimln_(10, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (((NI) 1) <= N);
		if (!(T7_)) goto LA8_;
		T7_ = (N <= ((NI) 100));
		LA8_: ;
		if (!!(T7_)) goto LA9_;
		failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__V45tF8B8NBcxFcjfe7lhBw_6));
	}
	LA9_: ;
	nimln_(11, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
	{
		NIM_BOOL T13_;
		NI T14_;
		NI T16_;
		T13_ = (NIM_BOOL)0;
		T14_ = (input_list ? input_list->Sup.len : 0);
		T13_ = (((NI) 1) <= T14_);
		if (!(T13_)) goto LA15_;
		T16_ = (input_list ? input_list->Sup.len : 0);
		T13_ = (T16_ <= N);
		LA15_: ;
		if (!!(T13_)) goto LA17_;
		failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__V45tF8B8NBcxFcjfe7lhBw_7));
	}
	LA17_: ;
	{
		NI* i;
		NI i_2;
		NI L;
		NI T20_;
		i = (NI*)0;
		nimln_(235, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators.nim");
		i_2 = ((NI) 0);
		nimln_(236, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators.nim");
		T20_ = (input_list ? input_list->Sup.len : 0);
		L = T20_;
		{
			nimln_(237, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators.nim");
			while (1) {
				NI TM__V45tF8B8NBcxFcjfe7lhBw_9;
				if (!(i_2 < L)) goto LA22;
				nimln_(12, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
				if (i_2 < 0 || i_2 >= (input_list ? input_list->Sup.len : 0)){ raiseIndexError2(i_2,(input_list ? input_list->Sup.len : 0)-1); }
				i = (&input_list->data[i_2]);
				nimln_(13, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
				{
					NIM_BOOL T25_;
					T25_ = (NIM_BOOL)0;
					T25_ = (((NI) 1) <= (*i));
					if (!(T25_)) goto LA26_;
					T25_ = ((*i) <= ((NI) 100));
					LA26_: ;
					if (!!(T25_)) goto LA27_;
					failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__V45tF8B8NBcxFcjfe7lhBw_8));
				}
				LA27_: ;
				nimln_(239, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__V45tF8B8NBcxFcjfe7lhBw_9)) { raiseOverflow(); };
				i_2 = (NI)(TM__V45tF8B8NBcxFcjfe7lhBw_9);
				nimln_(240, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators.nim");
				{
					NI T31_;
					T31_ = (input_list ? input_list->Sup.len : 0);
					if (!!((T31_ == L))) goto LA32_;
					failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__V45tF8B8NBcxFcjfe7lhBw_10));
				}
				LA32_: ;
			} LA22: ;
		}
	}
	nimln_(17, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
	sorted_list = sorted__OOZOOZmain_84((input_list) ? (input_list->data) : NIM_NIL, (input_list ? input_list->Sup.len : 0), ((tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA) 0));
	nimln_(19, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
	{
		NI T36_;
		T36_ = (sorted_list ? sorted_list->Sup.len : 0);
		if (!((NI)(T36_ % ((NI) 2)) == ((NI) 0))) goto LA37_;
		{
			NI i_3;
			NI colontmp_;
			NI T40_;
			NI i_4;
			i_3 = (NI)0;
			colontmp_ = (NI)0;
			nimln_(20, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
			T40_ = (sorted_list ? sorted_list->Sup.len : 0);
			colontmp_ = T40_;
			nimln_(119, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
			i_4 = ((NI) 0);
			{
				nimln_(120, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
				while (1) {
					NI TM__V45tF8B8NBcxFcjfe7lhBw_13;
					if (!(i_4 < colontmp_)) goto LA42;
					nimln_(20, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
					i_3 = i_4;
					{
						NI TM__V45tF8B8NBcxFcjfe7lhBw_12;
						nimln_(21, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
						{
							NIM_BOOL T46_;
							NI TM__V45tF8B8NBcxFcjfe7lhBw_11;
							T46_ = (NIM_BOOL)0;
							T46_ = (i_3 == ((NI) 0));
							if (T46_) goto LA47_;
							T46_ = ((NI)(i_3 % ((NI) 2)) == ((NI) 0));
							LA47_: ;
							if (!T46_) goto LA48_;
							nimln_(22, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
							if (i_3 < 0 || i_3 >= (sorted_list ? sorted_list->Sup.len : 0)){ raiseIndexError2(i_3,(sorted_list ? sorted_list->Sup.len : 0)-1); }
							if (nimAddInt(Alice_score, sorted_list->data[i_3], &TM__V45tF8B8NBcxFcjfe7lhBw_11)) { raiseOverflow(); };
							Alice_score = (NI)(TM__V45tF8B8NBcxFcjfe7lhBw_11);
							nimln_(23, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
							goto LA43;
						}
						LA48_: ;
						nimln_(24, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
						if (i_3 < 0 || i_3 >= (sorted_list ? sorted_list->Sup.len : 0)){ raiseIndexError2(i_3,(sorted_list ? sorted_list->Sup.len : 0)-1); }
						if (nimAddInt(Bob_score, sorted_list->data[i_3], &TM__V45tF8B8NBcxFcjfe7lhBw_12)) { raiseOverflow(); };
						Bob_score = (NI)(TM__V45tF8B8NBcxFcjfe7lhBw_12);
					} LA43: ;
					nimln_(122, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
					if (nimAddInt(i_4, ((NI) 1), &TM__V45tF8B8NBcxFcjfe7lhBw_13)) { raiseOverflow(); };
					i_4 = (NI)(TM__V45tF8B8NBcxFcjfe7lhBw_13);
				} LA42: ;
			}
		}
	}
	goto LA34_;
	LA37_: ;
	{
		{
			NI i_5;
			NI colontmp__2;
			NI T52_;
			NI i_6;
			i_5 = (NI)0;
			colontmp__2 = (NI)0;
			nimln_(26, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
			T52_ = (sorted_list ? sorted_list->Sup.len : 0);
			colontmp__2 = T52_;
			nimln_(119, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
			i_6 = ((NI) 0);
			{
				nimln_(120, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
				while (1) {
					NI TM__V45tF8B8NBcxFcjfe7lhBw_16;
					if (!(i_6 < colontmp__2)) goto LA54;
					nimln_(26, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
					i_5 = i_6;
					{
						NI TM__V45tF8B8NBcxFcjfe7lhBw_15;
						nimln_(27, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
						{
							NIM_BOOL T58_;
							NIM_BOOL T59_;
							NI T62_;
							NI TM__V45tF8B8NBcxFcjfe7lhBw_14;
							T58_ = (NIM_BOOL)0;
							T59_ = (NIM_BOOL)0;
							T59_ = (i_5 == ((NI) 0));
							if (T59_) goto LA60_;
							T59_ = ((NI)(i_5 % ((NI) 2)) == ((NI) 0));
							LA60_: ;
							T58_ = T59_;
							if (T58_) goto LA61_;
							T62_ = (sorted_list ? sorted_list->Sup.len : 0);
							T58_ = (i_5 == T62_);
							LA61_: ;
							if (!T58_) goto LA63_;
							nimln_(28, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
							if (i_5 < 0 || i_5 >= (sorted_list ? sorted_list->Sup.len : 0)){ raiseIndexError2(i_5,(sorted_list ? sorted_list->Sup.len : 0)-1); }
							if (nimAddInt(Alice_score, sorted_list->data[i_5], &TM__V45tF8B8NBcxFcjfe7lhBw_14)) { raiseOverflow(); };
							Alice_score = (NI)(TM__V45tF8B8NBcxFcjfe7lhBw_14);
							nimln_(29, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
							goto LA55;
						}
						LA63_: ;
						nimln_(30, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
						if (i_5 < 0 || i_5 >= (sorted_list ? sorted_list->Sup.len : 0)){ raiseIndexError2(i_5,(sorted_list ? sorted_list->Sup.len : 0)-1); }
						if (nimAddInt(Bob_score, sorted_list->data[i_5], &TM__V45tF8B8NBcxFcjfe7lhBw_15)) { raiseOverflow(); };
						Bob_score = (NI)(TM__V45tF8B8NBcxFcjfe7lhBw_15);
					} LA55: ;
					nimln_(122, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
					if (nimAddInt(i_6, ((NI) 1), &TM__V45tF8B8NBcxFcjfe7lhBw_16)) { raiseOverflow(); };
					i_6 = (NI)(TM__V45tF8B8NBcxFcjfe7lhBw_16);
				} LA54: ;
			}
		}
	}
	LA34_: ;
	nimln_(31, "/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/main.nim");
	nimZeroMem((void*)T65_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	if (nimSubInt(Alice_score, Bob_score, &TM__V45tF8B8NBcxFcjfe7lhBw_17)) { raiseOverflow(); };
	T65_[0] = dollar___systemZdollars_3((NI)(TM__V45tF8B8NBcxFcjfe7lhBw_17));
	echoBinSafe(T65_, 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsmaindotnim_DatInit000)(void) {
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.size = sizeof(tySequence__qwqHTkRvwhrRyENtudHQ7g*);
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.align = NIM_ALIGNOF(tySequence__qwqHTkRvwhrRyENtudHQ7g*);
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.kind = 24;
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.base = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.marker = Marker_tySequence__qwqHTkRvwhrRyENtudHQ7g;
}

