/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib -I/home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/tests/nim -o /home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/nimcache/tests/nim/test.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s.choosenim@stoolchains@snim-1.6.10@slib@ssystem@sio.nim.c.o /home/se0r12/Atcoder/AtCoder_Beginners_Selection/ABC088B/nimcache/tests/nim/test.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s.choosenim@stoolchains@snim-1.6.10@slib@ssystem@sio.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <errno.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_EOFError__KGSY1JdrNB7Xi8KDhXFhSg tyObject_EOFError__KGSY1JdrNB7Xi8KDhXFhSg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_EOFError__KGSY1JdrNB7Xi8KDhXFhSg {
  tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw Sup;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__systemZio_238)(FILE* f, NimStringDesc** line);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NIM_BOOL, eqeq___system_7770)(NCSTRING x, NCSTRING y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2997)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, checkErr__systemZio_141)(FILE* f);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__systemZio_96)(NimStringDesc* msg) __attribute__((noreturn));
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef__system_5344)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5342)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5293)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5299)(void* usr);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5337)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NOINLINE(void, raiseEOF__systemZio_117)(void) __attribute__((noreturn));
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
STRING_LITERAL(TM__MnCJ0VAmeZ9aTATUB39cx60Q_4, "errno: ", 7);
STRING_LITERAL(TM__MnCJ0VAmeZ9aTATUB39cx60Q_5, " `", 2);
STRING_LITERAL(TM__MnCJ0VAmeZ9aTATUB39cx60Q_6, "`", 1);
extern TNimType NTIrefioerror__HMIVdYjdZYWskTmTQVo5BQ_;
extern TNimType NTIioerror__iLZrPn9anoh9ad1MmO0RczFw_;
extern TNimType NTIrefeoferror__LEclZrWX2FQAodlapxGITw_;
extern TNimType NTIeoferror__KGSY1JdrNB7Xi8KDhXFhSg_;
STRING_LITERAL(TM__MnCJ0VAmeZ9aTATUB39cx60Q_18, "EOF reached", 11);
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern TFrame* framePtr__system_2564;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5246;
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2564 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2564).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2564;
	framePtr__system_2564 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2997();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2564 = (*framePtr__system_2564).prev;
}
static N_INLINE(NIM_BOOL, eqeq___system_7770)(NCSTRING x, NCSTRING y) {
	NIM_BOOL result;
	nimfr_("==", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system.nim");
	result = (NIM_BOOL)0;
	nimln_(2994, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system.nim");
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(2995, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system.nim");
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		nimln_(2996, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system.nim");
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/arithmetics.nim");
	nimln_(418, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/comparisons.nim");
	result = (NIM_BOOL)0;
	nimln_(186, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/comparisons.nim");
	nimln_(188, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/comparisons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5342)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	nimln_(243, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	addZCT__system_5293((&gch__system_5246.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__system_5344)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	nimln_(248, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	nimln_(249, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(250, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
		rtlAddZCT__system_5342(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5299)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(177, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefNoCycle", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	nimln_(276, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5299(p);
	decRef__system_5344(T1_);
	popFrame();
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	nimfr_("+%", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/arithmetics.nim");
	result = (NI)0;
	nimln_(403, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/arithmetics.nim");
	nimln_(407, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__system_5337)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	nimln_(231, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	nimln_(286, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5299(src);
		incRef__system_5337(T5_);
	}
	LA3_: ;
	nimln_(287, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5299((*dest));
		decRef__system_5344(T10_);
	}
	LA8_: ;
	nimln_(288, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/gc.nim");
	(*dest) = src;
	popFrame();
}
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__systemZio_96)(NimStringDesc* msg) {
	tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw* T1_;
	NimStringDesc* T2_;
	nimfr_("raiseEIO", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	T1_ = NIM_NIL;
	T1_ = (tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw*) newObj((&NTIrefioerror__HMIVdYjdZYWskTmTQVo5BQ_), sizeof(tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIioerror__iLZrPn9anoh9ad1MmO0RczFw_);
	(*T1_).Sup.Sup.name = "IOError";
	T2_ = NIM_NIL;
	T2_ = (*T1_).Sup.Sup.message; (*T1_).Sup.Sup.message = copyStringRC1(msg);
	if (T2_) nimGCunrefNoCycle(T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.parent), ((Exception*) NIM_NIL));
	nimln_(153, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	raiseExceptionEx((Exception*)T1_, "IOError", "raiseEIO", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim", 153);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, checkErr__systemZio_141)(FILE* f) {
	nimfr_("checkErr", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	nimln_(167, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	{
		int T3_;
		NimStringDesc* msg;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		NCSTRING T8_;
		NimStringDesc* T9_;
		T3_ = (int)0;
		T3_ = ferror(f);
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(168, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
		T6_ = NIM_NIL;
		T7_ = NIM_NIL;
		T7_ = dollar___systemZdollars_3(((NI) (errno)));
		T8_ = (NCSTRING)0;
		T8_ = strerror(errno);
		T9_ = NIM_NIL;
		T9_ = cstrToNimstr(T8_);
		T6_ = rawNewString((T7_ ? T7_->Sup.len : 0) + (T9_ ? T9_->Sup.len : 0) + 10);
appendString(T6_, ((NimStringDesc*) &TM__MnCJ0VAmeZ9aTATUB39cx60Q_4));
appendString(T6_, T7_);
appendString(T6_, ((NimStringDesc*) &TM__MnCJ0VAmeZ9aTATUB39cx60Q_5));
appendString(T6_, T9_);
appendString(T6_, ((NimStringDesc*) &TM__MnCJ0VAmeZ9aTATUB39cx60Q_6));
		msg = T6_;
		nimln_(169, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
		clearerr(f);
		nimln_(170, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
		raiseEIO__systemZio_96(msg);
	}
	LA4_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__systemZio_238)(FILE* f, NimStringDesc** line) {
	NIM_BOOL result;
	NI pos;
	NI sp;
	nimfr_("readLine", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
{	result = (NIM_BOOL)0;
	nimln_(449, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	pos = ((NI) 0);
	nimln_(452, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	sp = ((((*line) ? (*line)->Sup.len : 0) >= ((NI) 80)) ? ((*line) ? (*line)->Sup.len : 0) : ((NI) 80));
	nimln_(453, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	if ((sp) < ((NI) 0) || (sp) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(sp, ((NI) 0), ((NI) IL64(9223372036854775807))); }
	unsureAsgnRef((void**) (&(*line)), setLengthStr((*line), ((NI) (sp))));
	{
		nimln_(455, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
		while (1) {
			NIM_BOOL fgetsSuccess;
			void* m;
			NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_16;
			NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_17;
			{
				NI i;
				NI i_2;
				i = (NI)0;
				nimln_(119, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
				i_2 = ((NI) 0);
				{
					nimln_(120, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
					while (1) {
						NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_2;
						NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_3;
						if (!(i_2 < sp)) goto LA5;
						nimln_(458, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
						i = i_2;
						if (nimAddInt(pos, i, &TM__MnCJ0VAmeZ9aTATUB39cx60Q_2)) { raiseOverflow(); };
						if ((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_2) < 0 || (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_2) >= ((*line) ? (*line)->Sup.len : 0)){ raiseIndexError2((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_2),((*line) ? (*line)->Sup.len : 0)-1); }
						(*line)->data[(NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_2)] = 10;
						nimln_(122, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators_1.nim");
						if (nimAddInt(i_2, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_3)) { raiseOverflow(); };
						i_2 = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_3);
					} LA5: ;
				}
			}
			fgetsSuccess = (NIM_BOOL)0;
			{
				nimln_(461, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
				while (1) {
					{
						NCSTRING T9_;
						NIM_BOOL T10_;
						nimln_(464, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
						if (pos < 0 || pos >= ((*line) ? (*line)->Sup.len : 0)){ raiseIndexError2(pos,((*line) ? (*line)->Sup.len : 0)-1); }
						if ((sp) < ((int) (-2147483647 -1)) || (sp) > ((int) 2147483647)){ raiseRangeErrorI(sp, ((int) (-2147483647 -1)), ((int) 2147483647)); }
						T9_ = (NCSTRING)0;
						T9_ = fgets(((NCSTRING) ((&(*line)->data[pos]))), ((int) (sp)), f);
						T10_ = (NIM_BOOL)0;
						T10_ = eqeq___system_7770(T9_, ((NCSTRING) NIM_NIL));
						fgetsSuccess = !(T10_);
						nimln_(465, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
						{
							if (!fgetsSuccess) goto LA13_;
							goto LA6;
						}
						LA13_: ;
						nimln_(467, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
						{
							if (!(errno == EINTR)) goto LA17_;
							nimln_(468, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
							errno = ((int) 0);
							nimln_(469, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
							clearerr(f);
							nimln_(470, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
							goto LA8;
						}
						LA17_: ;
						nimln_(471, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
						checkErr__systemZio_141(f);
						nimln_(472, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
						goto LA6;
					} LA8: ;
				}
			} LA6: ;
			nimln_(474, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
			if (pos < 0 || pos >= ((*line) ? (*line)->Sup.len : 0)){ raiseIndexError2(pos,((*line) ? (*line)->Sup.len : 0)-1); }
			m = memchr(((void*) ((&(*line)->data[pos]))), ((int) 10), ((size_t) (sp)));
			nimln_(475, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
			{
				NI last;
				NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_7;
				NIM_BOOL T42_;
				if (!!((m == NIM_NIL))) goto LA21_;
				nimln_(477, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
				if (((NI) 0) < 0 || ((NI) 0) >= ((*line) ? (*line)->Sup.len : 0)){ raiseIndexError2(((NI) 0),((*line) ? (*line)->Sup.len : 0)-1); }
				if (nimSubInt(((NI) (ptrdiff_t) (m)), ((NI) (ptrdiff_t) ((&(*line)->data[((NI) 0)]))), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_7)) { raiseOverflow(); };
				last = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_7);
				nimln_(478, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
				{
					NIM_BOOL T25_;
					NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_8;
					NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_9;
					NIM_BOOL T29_;
					T25_ = (NIM_BOOL)0;
					T25_ = (((NI) 0) < last);
					if (!(T25_)) goto LA26_;
					if (nimSubInt(last, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_8)) { raiseOverflow(); };
					if ((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_8) < 0 || (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_8) >= ((*line) ? (*line)->Sup.len : 0)){ raiseIndexError2((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_8),((*line) ? (*line)->Sup.len : 0)-1); }
					T25_ = ((NU8)((*line)->data[(NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_8)]) == (NU8)(13));
					LA26_: ;
					if (!T25_) goto LA27_;
					nimln_(479, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
					if (nimSubInt(last, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_9)) { raiseOverflow(); };
					if (((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_9)) < ((NI) 0) || ((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_9)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_9), ((NI) 0), ((NI) IL64(9223372036854775807))); }
					unsureAsgnRef((void**) (&(*line)), setLengthStr((*line), ((NI) ((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_9)))));
					nimln_(480, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
					T29_ = (NIM_BOOL)0;
					T29_ = (((NI) 1) < last);
					if (T29_) goto LA30_;
					T29_ = fgetsSuccess;
					LA30_: ;
					result = T29_;
					goto BeforeRet_;
				}
				goto LA23_;
				LA27_: ;
				{
					NIM_BOOL T32_;
					NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_10;
					nimln_(484, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
					T32_ = (NIM_BOOL)0;
					T32_ = (((NI) 0) < last);
					if (!(T32_)) goto LA33_;
					if (nimSubInt(last, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_10)) { raiseOverflow(); };
					if ((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_10) < 0 || (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_10) >= ((*line) ? (*line)->Sup.len : 0)){ raiseIndexError2((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_10),((*line) ? (*line)->Sup.len : 0)-1); }
					T32_ = ((NU8)((*line)->data[(NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_10)]) == (NU8)(0));
					LA33_: ;
					if (!T32_) goto LA34_;
					nimln_(485, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
					{
						NIM_BOOL T38_;
						NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_11;
						NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_12;
						NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_13;
						NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_14;
						T38_ = (NIM_BOOL)0;
						if (nimAddInt(pos, sp, &TM__MnCJ0VAmeZ9aTATUB39cx60Q_11)) { raiseOverflow(); };
						if (nimSubInt((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_11), ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_12)) { raiseOverflow(); };
						T38_ = (last < (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_12));
						if (!(T38_)) goto LA39_;
						if (nimAddInt(last, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_13)) { raiseOverflow(); };
						if ((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_13) < 0 || (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_13) >= ((*line) ? (*line)->Sup.len : 0)){ raiseIndexError2((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_13),((*line) ? (*line)->Sup.len : 0)-1); }
						T38_ = !(((NU8)((*line)->data[(NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_13)]) == (NU8)(0)));
						LA39_: ;
						if (!T38_) goto LA40_;
						nimln_(486, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
						if (nimSubInt(last, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_14)) { raiseOverflow(); };
						last = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_14);
					}
					LA40_: ;
				}
				goto LA23_;
				LA34_: ;
				LA23_: ;
				nimln_(487, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
				if ((last) < ((NI) 0) || (last) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(last, ((NI) 0), ((NI) IL64(9223372036854775807))); }
				unsureAsgnRef((void**) (&(*line)), setLengthStr((*line), ((NI) (last))));
				nimln_(488, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
				T42_ = (NIM_BOOL)0;
				T42_ = (((NI) 0) < last);
				if (T42_) goto LA43_;
				T42_ = fgetsSuccess;
				LA43_: ;
				result = T42_;
				goto BeforeRet_;
			}
			goto LA19_;
			LA21_: ;
			{
				NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_15;
				nimln_(491, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
				if (nimSubInt(sp, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_15)) { raiseOverflow(); };
				sp = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_15);
			}
			LA19_: ;
			nimln_(493, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
			if (nimAddInt(pos, sp, &TM__MnCJ0VAmeZ9aTATUB39cx60Q_16)) { raiseOverflow(); };
			pos = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_16);
			nimln_(494, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
			sp = ((NI) 128);
			nimln_(495, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
			if (nimAddInt(pos, sp, &TM__MnCJ0VAmeZ9aTATUB39cx60Q_17)) { raiseOverflow(); };
			if (((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_17)) < ((NI) 0) || ((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_17)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_17), ((NI) 0), ((NI) IL64(9223372036854775807))); }
			unsureAsgnRef((void**) (&(*line)), setLengthStr((*line), ((NI) ((NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_17)))));
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseEOF__systemZio_117)(void) {
	tyObject_EOFError__KGSY1JdrNB7Xi8KDhXFhSg* T1_;
	NimStringDesc* T2_;
	nimfr_("raiseEOF", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	T1_ = NIM_NIL;
	T1_ = (tyObject_EOFError__KGSY1JdrNB7Xi8KDhXFhSg*) newObj((&NTIrefeoferror__LEclZrWX2FQAodlapxGITw_), sizeof(tyObject_EOFError__KGSY1JdrNB7Xi8KDhXFhSg));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIeoferror__KGSY1JdrNB7Xi8KDhXFhSg_);
	(*T1_).Sup.Sup.Sup.name = "EOFError";
	T2_ = NIM_NIL;
	T2_ = (*T1_).Sup.Sup.Sup.message; (*T1_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__MnCJ0VAmeZ9aTATUB39cx60Q_18));
	if (T2_) nimGCunrefNoCycle(T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	nimln_(156, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	raiseExceptionEx((Exception*)T1_, "EOFError", "raiseEOF", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim", 156);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine__systemZio_271)(FILE* f) {
	NimStringDesc* result;
	nimfr_("readLine", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	result = NIM_NIL;
	nimln_(501, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	result = rawNewString(((NI) 80));
	nimln_(502, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = readLine__systemZio_238(f, (&result));
		if (!!(T3_)) goto LA4_;
		raiseEOF__systemZio_117();
	}
	LA4_: ;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0) {
	size_t T5_;
	int T6_;
	nimfr_("echoBinSafe", "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	nimln_(815, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	flockfile(stdout);
	{
		NimStringDesc** s;
		NI i;
		s = (NimStringDesc**)0;
		nimln_(8, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators.nim");
		i = ((NI) 0);
		{
			nimln_(9, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators.nim");
			while (1) {
				size_t T4_;
				NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_19;
				if (!(i < argsLen_0)) goto LA3;
				nimln_(818, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
				if (i < 0 || i >= argsLen_0){ raiseIndexError2(i,argsLen_0-1); }
				s = (&args[i]);
				nimln_(822, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
				nimln_(818, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
				T4_ = (size_t)0;
				T4_ = fwrite(((void*) (nimToCStringConv((*s)))), ((size_t) (((*s) ? (*s)->Sup.len : 0))), ((size_t) 1), stdout);
				(void)(T4_);
				nimln_(11, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/iterators.nim");
				if (nimAddInt(i, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_19)) { raiseOverflow(); };
				i = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_19);
			} LA3: ;
		}
	}
	nimln_(824, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	T5_ = (size_t)0;
	T5_ = fwrite(((void*) ("\012")), ((size_t) 1), ((size_t) 1), stdout);
	(void)(T5_);
	nimln_(825, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	T6_ = (int)0;
	T6_ = fflush(stdout);
	(void)(T6_);
	nimln_(827, "/home/se0r12/.choosenim/toolchains/nim-1.6.10/lib/system/io.nim");
	funlockfile(stdout);
	popFrame();
}
